// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jentttucsvqmodbjrtqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbnR0dHVjc3ZxbW9kYmpydHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MzU2MTIsImV4cCI6MjA4NjAxMTYxMn0.-2fWi6XfrygQ-VfnyXbI2bHoVwGm-b9ouNbmriyi4Lo";

// Supabase is always configured since we have hardcoded credentials
export const isSupabaseConfigured = true;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper to get the Supabase client (for consistency with optional config patterns)
export const requireSupabase = (): SupabaseClient<Database> => {
  return supabase;
};